### ISSUE TITLE
Consider using the HTCondor python interface

### ISSUE THREAD

**Issue by annawoodard** [Parsl/libsubmit#10]
As HTCondor support in libsubmit grows, consider using the HTCondor python [interface](http://htcondor-python.readthedocs.io/en/latest/). For example, rather pushing the config and executing "condor_submit" on the remote side you'd push a python script and execute that. It has a few advantages: a nice pythonic interface, good error handling, good support for `ClassAds`, more straightforward implementation if multiple commands are to be chained together, etc. Also, it might be convenient for debugging, because both the execution commands and the submit config would be recorded on the remote side, rather than just the config, so if an error was encountered, the dev/user could exactly reproduce it by logging in on the remote side and running the script.

**Comment by yadudoc** [comment]
Copying over from a conversation : 
The concern here is that the HTCondor python interface works nicely if you are on the login node, however it is unclear as to how this would work if the submit node is remote. In our current model of using scripts and commands over local/ssh channels we don't have to rely on bootstrapping python on the login node. We only need to worry about the the python environment of the compute nodes.

My concern is that this will add way more complexity for not so much value (at this point).

Once we have a few condor users, I would revisit this. What do you think @annawoodard  ?

**Comment by annawoodard** [comment]
That makes sense to me @yadudoc! I'll close it for now and we can re-open if a clear need for it arises.
