### ISSUE TITLE
This needs to be better explained

### ISSUE THREAD

**Issue by danielskatz** [Parsl/libsubmit#11]
https://github.com/Parsl/libsubmit/blob/790662124e60461e25d5ed64af58ccac00368203/libsubmit/execution_provider_base.py#L28

> We haven’t yet decided on what the args to this can be, whether it should just be func, args, kwargs or be the partially evaluated fn

Should `fn` be `func`? 

Does `partially evaluated fn` need to be better explained?

**Comment by danielskatz** [comment]
this applies to all similar instances of this text in this file, such as in lines 41-43, 61-63, etc.

**Comment by yadudoc** [comment]
Fixed.
