### ISSUE TITLE
Support for async execution

### ISSUE THREAD

**Issue by yadudoc** [Parsl/libsubmit#21]
The async execution options provided via channels are inadequate, incomplete and untested.
The execute_no_wait calls should ideally return a handle, which can be polled for completion and blocked on to receive results.

- [x] Update execute_no_wait interface
- [x] Add poll_handle() method to do a non-blocking check of status of a handle
- [ ] Add result() method that blocks on the handle to return results from an async execution

**Comment by yadudoc** [comment]
Calling this done, for now. Deferring the result bit for 0.4

**Comment by benclifford** [comment]
`execute_no_wait`  was removed in #1629 - closing this issue as irrelevant.
