### ISSUE TITLE
Validate configuration options on initialization

### ISSUE THREAD

**Issue by annawoodard** [Parsl/libsubmit#22]
Feedback via the Slack help channel from a user trying to run on Slurm:
> For a parsl configuration dictionary, what is `config['sites']['execution']['scriptDir']`? I'm trying to run on a slurm cluster but it's telling me
> ```
> libsubmit.channels.errors.BadScriptPath: Hostname:192.170.228.90, Reason:Inaccessible remote script dir. Specify script_dir
> ```
> Do I need to have slurm script pre-made?

We should clarify that this is a configuration error. It would be good to validate the entire configuration on initialization of the `ExecutionProvider`. This has two advantages:

1) Failing as early as possible would avoid doing unnecessary work.
2) The error will point to where the user instantiates the `ExecutionProvider` (which is where the user needs to make a modification to fix the problem) rather than where the options are used (which would require the user to read the source code to understand).

This is related to #9 but I think it makes sense to keep these factorized. I vote to have a dedicated class `ConfigurationError` or something like that.

The resolution to this issue should meet the following requirements:
1. Provide error messages which are clear enough to avoid the user confusion above
2. Validation of each option should only happen in one place
  
EDIT: Added more of the original context from the user

**Comment by annawoodard** [comment]
(@yadudoc if there is support for this, feel free to assign me and I will implement it as I'm getting up to speed)

**Comment by yadudoc** [comment]
I'm pushing most of the config logic into `parsl/dataflow/config_defaults.py` in the `flowcontrol` branch.
This currently just sets some defaults that are common across all providers and possible site definitions.

We need some sort of conditional schema, where given a specific provider, provider specific defaults as well as limits/checks are done. This sort of config schema should be specified in the provider and imported up by the config checker.

I think catching errors early and letting the user know would be a super useful feature to have. I'd be happy if you could take a stab at this.

**Comment by annawoodard** [comment]
> We need some sort of conditional schema, where given a specific provider, provider specific defaults as well as limits/checks are done. This sort of config schema should be specified in the provider and imported up by the config checker.

Sounds good @yadudoc! I've got some ideas for how this could go. I'll make a quick sketch and push the branch up to get feedback from you before finalizing things. (Note I'm in the thesis-writing-cave currently, so won't get to this until next month, unfortunately)

**Comment by annawoodard** [comment]
Note that a similar issue came up today, reported by @bakerjl.
