### ISSUE TITLE
Condor provider with local channel fails.

### ISSUE THREAD

**Issue by yadudoc** [Parsl/libsubmit#24]
Condor provider fails when used with local channels. Reported by Michael Wang

**Comment by yadudoc** [comment]
When we added changes to ssh channels to take env variables, we did not add the same support to local channels and update channel_base to a consistent interface. This led to the condor provider calling the local channel with parameters it had not defined.

**Comment by annawoodard** [comment]
:woman_facepalming: Yikes, my bad. Sorry about that!

**Comment by yadudoc** [comment]
This fix is available in the libsubmit 0.2.6.
