### ISSUE TITLE
Compatibility with Python3.4

### ISSUE THREAD

**Issue by yadudoc** [Parsl/libsubmit#33]
Libsubmit is pretty light and does not use much of the advanced features in Python3.5+ like Parsl.
Most version incompatibility is from using newer syntax, which could be fixed.

**Comment by LincolnBryant** [comment]
:+1: 

thanks for opening this issue. with your latest commits I am successful in at least importing libsubmit from EPEL's Python 3.4 package on CentOS 7:

```
$ python3.4
Python 3.4.5 (default, Dec 11 2017, 14:22:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsubmit
>>> 
```

**Comment by yadudoc** [comment]
I'm calling this closed, untill @LincolnBryant reports an issue with 3.4
