### ISSUE TITLE
Walltime not set correctly in torque provider

### ISSUE THREAD

**Issue by daheise** [Parsl/libsubmit#72]
[The walltime for torque is given in minutes](https://github.com/Parsl/libsubmit/blob/f1e408f8da8c07b23cb4d2d924c566f4a0928a56/libsubmit/providers/torque/torque.py#L190), however, torque interprets a bare integer without additional time formatting as seconds.

**Comment by annawoodard** [comment]
Good catch, @daheise. Thanks for the report and solution!
