### ISSUE TITLE
LocalProvider Initialized with Default Arguments, even when using TorqueProvider

### ISSUE THREAD

**Issue by daheise** [Parsl/libsubmit#74]
I am using the `IPyParallelExecutor`, `TorqueProvider`, and `SSHChannel`. 

I have set the `engine_dir` to the Executor, and the `script_dir` to the Provider explicitly.

When executing my workflow I see the error `ipyparallel.error.RemoteError: FileExistsError([Errno 17] File exists: 'parsl_scripts').`

I looked at the traceback in the ipengine log and see the source of the error is [this line](https://github.com/Parsl/libsubmit/blob/master/libsubmit/providers/local/local.py#L62) in the `LocalProvider`.

Changing the line to `os.makedirs(script_dir, exist_ok=True)` allows the workflow to complete successfully, however I do not understand why a `LocalProvider` is being initialized at all, nor why the guard on line 61 is not preventing the error. The traceback indicates the `LocalProviders` origin follows this path:

1. https://github.com/Parsl/parsl/blob/master/parsl/__init__.py#L31
2. https://github.com/Parsl/parsl/blob/master/parsl/executors/ipp.py#L18
3. https://github.com/Parsl/parsl/blob/master/parsl/executors/ipp.py#L70
4. https://github.com/Parsl/libsubmit/blob/master/libsubmit/providers/local/local.py#L62

After adding `exist_ok=True`, while the `parsl_scripts` directory is created in the location the workflow is executed from, it is empty.

**Comment by daheise** [comment]
Could this line in the representation mixin be causing the IPyParallelExecutor to be initialized with the default arguments?

https://github.com/Parsl/libsubmit/blob/master/libsubmit/utils.py#L47

**Comment by annawoodard** [comment]
Thanks for the report, @daheise! Can you post your configuration?
