### ISSUE TITLE
Clarify `ExecutionProvider` config documentation

### ISSUE THREAD

**Issue by annawoodard** [Parsl/libsubmit#9]
I played around with libsubmit a bit-- it is a great library! I'm really excited about the possibilities here!

I have some very minor feedback. From a new-user perspective it might be preferable to have separate constructor parameters for the config components rather than one dictionary. In that way all of the required options, optional options, and defaults can be documented more clearly (from [this](https://github.com/Parsl/libsubmit/blob/master/libsubmit/providers/condor/condor.py#L30-L52) it's hard to be sure the example is showing the defaults, and it's hard to include descriptions). Users could still pass the arguments as a dictionary in the same way for convenience, the big change would be clearer documentation. Here's a sketch:

```python
class Foo(object):
    def __init__(self, baz, first='a', second='b'):
        '''Initialize the Foo class

        Args:
            first : string
                Explanation of first. The default values are clear from above.
                If needed, we can talk for a long time about first! Here's some
                more details.
            second : string
                Explanation of second.
        '''
        self.baz = baz
        self.first = first
        self.second = second


class Bar(object):
    def __init__(self, baz, config):
        '''Initialize the Bar class

        Args:
            config : dict
                Dictionary with config options. For example:

                config = {
                    'first': 'a',  # Explanation of first. Is 'a' the default? If we
                                   # need to say more than a few words, it gets kind of confusing.
                    'second': 'b'
                }
        '''
        self.baz = baz
        self.first = config.get('first', 'a')
        self.second = config.get('second', 'b')


config = {
    'first': 'c',
    'second': 'd'
}

foo = Foo('test', **config)
bar = Bar('test', config)
```

**Comment by yadudoc** [comment]
This is a hard one!  Ideally, we are able to distill the greatest common denominator of the resource descriptions for all kinds of compute resources and set that up with uniform defaults. Often this is very small compared to what the user might wish to request from a particular resource, and that led to a nested config instead of a flat dictionary. The resource/scheduler specific options, going under execution.block.options = {}. 

I know that this documentation problem needs to be dealt with if this library were to be useful for users. I'm not quite sure how the wrapper class above would dealt with nested arguments. I'm open to ideas on how to expose this better.

**Comment by annawoodard** [comment]
@yadudoc @kylechard It was great meeting you both today!

@yadudoc: That's a good point, thanks for the clear explanation. One thing that's worked well for us on Lobster is to use simple classes for specifying the config. So [Config](http://lobster.readthedocs.io/en/latest/config.html#lobster.core.config.Config) would be analogous to the first level of your config dictionary and [AdvancedOptions](http://lobster.readthedocs.io/en/latest/config.html#lobster.core.config.AdvancedOptions) would be analogous to a nested level, for example:

```python
config = Config(
    workdir='/tmpscratch/users/$USER/lobster_mc_' + version,
    plotdir='~/www/lobster/mc_' + version,
    storage=storage,
    workflows=[lhe, gs, digi, reco, maod],
    advanced=AdvancedOptions(log_level=1)
)
```
In your case you could have something like an `ExecutionConfig` class and a `BlockConfig` class.

> Ideally, we are able to distill the greatest common denominator of the resource descriptions for all kinds of compute resources and set that up with uniform defaults. Often this is very small compared to what the user might wish to request from a particular resource, and that led to a nested config instead of a flat dictionary.

That's exactly why, for me, constructor parameters are clearer: non-required can be set to `None`, and defaults and required options are listed explicitly. If that sort of approach doesn't seem like a good fit, I'll keep brainstorming and let you know if I come up with any other ideas. This isn't critical, just a minor issue that jumped out at me as a new user-- it wasn't totally clear without looking at the source in addition to the documentation to figure out what the appropriate settings for my situation were.

**Comment by annawoodard** [comment]
> Ideally, we are able to distill the greatest common denominator of the resource descriptions for all kinds of compute resources and set that up with uniform defaults. Often this is very small compared to what the user might wish to request from a particular resource, and that led to a nested config instead of a flat dictionary.

A small set of common options/defaults and then a larger set of specific options/defaults makes me think this might be exactly the kind of situation where a dedicated class would be preferable to a vanilla dictionary. I'll modify the proposal above: we could have `Mixin` classes to specify/validate/set defaults for common sets of config options using composition. Then specific options would be handled in the i.e. `ExecutionProvider` constructors.

I'm brainstorming ways to avoid the user confusion that prompted #22. Dictionaries are easier for _us_, but I am worried that flexibility comes at the expense of user-friendliness. This is definitely very low priority. Also, there's a high cost to breaking existing workflows, so we shouldn't make any big changes unless there's a substantial benefit. If it you don't have any objections, go ahead and assign me this issue. I'll incorporate the `Mixin` idea into the quick sketch I make for #22 and see what you think. Then if everyone agrees the benefit would be worth it, I'll finalize it concurrently with #22. If not, I'll abandon the `Mixin` idea and just tweak the `ExecutionProvider` docstrings for clarity.

**Comment by annawoodard** [comment]
Here is some user feedback from the Slack channel:

> I don't know that I have anything specific, I just feel like I don't know how to do anything related to configuration haha
> Like, I don't know what's required, what's possible, etc
> It seems to me that configuration is very specific to the platform the script is being run on, so maybe try to address a couple different possible configurations for different platforms?
